# Generated by Django 5.0 on 2023-12-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferrovia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=150)),
                ('origem', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
            ],
        ),
    ]
