# Generated by Django 5.0 on 2023-12-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferrovia', '0003_passagems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='c_permissao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='g_permissao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
